apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
  adminPassword: {{ .Values.secrets.adminPassword | quote }}
  s3AccessKey: {{ .Values.secrets.s3AccessKey | quote }}
  s3SecretKey: {{ .Values.secrets.s3SecretKey | quote }}
  oidcClientSecret: {{ .Values.secrets.oidcClientSecret | quote }}
  secretsKey: {{ .Values.secrets.secretsKey | quote }}
