import React from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  BarChart3,
  Bell,
  BellOff,
  Box,
  Check,
  ChevronRight,
  CircuitBoard,
  ClipboardList,
  CreditCard,
  ExternalLink,
  Gauge,
  Globe,
  HardDrive,
  LayoutDashboard,
  LogIn,
  LogOut,
  Lock,
  Play,
  Power,
  Radio,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Skull,
  Sparkles,
  Tag,
  Upload,
  Volume2,
  VolumeX,
  X,
  Zap,
  Flame,
  Microscope,
  Bug,
  Fingerprint,
  GitPullRequest,
  Radar,
  Compass,
  Download,
  Share2,
  Trash2,
  TrendingDown,
  TrendingUp,
} from 'lucide-react'
import type { View } from './nav'

const NAV_ICONS: Record<View, LucideIcon> = {
  overview: LayoutDashboard,
  issues: AlertTriangle,
  events: Zap,
  devices: HardDrive,
  releases: Upload,
  artifacts: Archive,
  hardware: CircuitBoard,
  boots: Power,
  alerts: Radio,
  channels: Tag,
  relays: ArrowLeftRight,
  projects: Box,
  dead: Skull,
  audit: ClipboardList,
  settings: Settings,
  analytics: BarChart3,
  compliance: Shield,
  billing: CreditCard,
  blog: ExternalLink,
  faq: Activity,
  docs: ClipboardList,
  pricing: Gauge,
  'fleet-health': Gauge,
  'device-dna': Fingerprint,
  pr: GitPullRequest,
  chaos: Bug,
  'lep-explorer': Compass,
  'memorial-wall': Flame,
  'public-api': ExternalLink,
  anomaly: Radar,
}

export function NavIcon({ view, size = 16 }: { view: View; size?: number }) {
  const Icon = NAV_ICONS[view] || Activity
  return <Icon size={size} strokeWidth={1.75} className="nav-icon" aria-hidden />
}

export {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  BellOff,
  Check,
  ChevronRight,
  CreditCard,
  Download,
  Upload,
  ExternalLink,
  Gauge,
  Globe,
  Lock,
  LogIn,
  LogOut,
  Play,
  RefreshCw,
  Search,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Trash2,
  TrendingDown,
  TrendingUp,
  Volume2,
  VolumeX,
  X,
  Flame,
  Microscope,
  Bug,
  Fingerprint,
  GitPullRequest,
  Radar,
  Compass,
}
