import React from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  BarChart3,
  Bell,
  BellOff,
  Box,
  Check,
  ChevronRight,
  CircuitBoard,
  ClipboardList,
  ExternalLink,
  Gauge,
  HardDrive,
  LayoutDashboard,
  LogIn,
  LogOut,
  Power,
  Radio,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Skull,
  Sparkles,
  Tag,
  Upload,
  Volume2,
  VolumeX,
  X,
  Zap,
} from 'lucide-react'
import type { View } from './nav'

const NAV_ICONS: Record<View, LucideIcon> = {
  overview: LayoutDashboard,
  issues: AlertTriangle,
  events: Zap,
  devices: HardDrive,
  releases: Upload,
  artifacts: Archive,
  hardware: CircuitBoard,
  boots: Power,
  alerts: Radio,
  channels: Tag,
  relays: ArrowLeftRight,
  projects: Box,
  dead: Skull,
  audit: ClipboardList,
  settings: Settings,
  analytics: BarChart3,
  compliance: Shield,
}

export function NavIcon({ view, size = 16 }: { view: View; size?: number }) {
  const Icon = NAV_ICONS[view] || Activity
  return <Icon size={size} strokeWidth={1.75} className="nav-icon" aria-hidden />
}

export {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  BellOff,
  Check,
  ChevronRight,
  ExternalLink,
  Gauge,
  LogIn,
  LogOut,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Volume2,
  VolumeX,
  X,
}
